name: "sccache action - speedup Rust GitHub actions"
description: "A GitHub Action that speeds up Rust compilation with sccache."
inputs:
  cache-key:
    description: "The cache key."
    default: "sccache"
  cache-save:
    description: "A Flag that indicates whether or not saving the cache"
    default: true
  cache-update:
    description: "A Flag that indicates whether or not updating cache when hit"
    default: true
  release-name:
    description: "The sccache version. e.g. v0.3.0"
    default: "latest"
  arch:
    description: "The sccache binary architecture."
    default: ""
runs:
  using: "node16"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
branding:
  icon: "archive"
  color: "black"
